# Generated by Django 4.1.7 on 2023-11-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.CharField(default='admin', max_length=50),
        ),
    ]
