"""
Django settings for gold_medal_statistics project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
DIR = os.path.abspath(os.path.dirname(__file__))
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = os.getenv("SECRET_KEY", 0)
SECRET_KEY = 'django-insecure-fiic!03nz8w*_$j7(qlueb+=0dw0!=k_*)k6n+!_35ekap+2=w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['gold-medal-statistics-e113a752d5f0.herokuapp.com', '127.0.0.1']

# Application definition

INSTALLED_APPS = [
    'marks.apps.MarksConfig',
    'users.apps.UsersConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'bootstrap4',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gold_medal_statistics.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gold_medal_statistics.wsgi.application'
CRISPY_TEMPLATE_PACK = 'bootstrap4'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# parse database configuration from $DATABASE_URL
import dj_database_url

if 'JAWSDB_URL' in os.environ:
    DATABASES = {
        'default': dj_database_url.config(default=os.getenv("JAWSDB_AQUA_URL", 0)),
        'marks': dj_database_url.config(default=os.getenv("JAWSDB_URL", 0)),
        'users': dj_database_url.config(default=os.getenv("JAWSDB_AQUA_URL", 0))
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'users',
            'USER': 'root',
            'PASSWORD': 'admin',
            'HOST': '127.0.0.1',
            'PORT': '3306',
            'OPTIONS': {  
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
                'ssl': True,
            }
        },
        'marks': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'marks',
            'USER': 'root',
            'PASSWORD': 'admin',
            'HOST': '127.0.0.1',
            'PORT': '3306',
            'OPTIONS': {  
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
                'ssl': True,
            }
        },
        'users': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'users',
            'USER': 'root',
            'PASSWORD': 'admin',
            'HOST': '127.0.0.1',
            'PORT': '3306',
            'OPTIONS': {  
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
                'ssl': True,
            }
        }
    }

DATABASE_ROUTERS = ['marks.db_router.MarksDBRouter', 'users.db_router.UsersDBRouter']

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGIN_REDIRECT_URL =  '/home'

LOGIN_URL = '/login'

AUTHENTICATION_BACKENDS = [
   'django.contrib.auth.backends.ModelBackend',
]

AUTH_USER_MODEL = "users.User"

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Session management
SESSION_COOKIE_AGE = 14400 # required login every 4 hours

SESSION_SAVE_EVERY_REQUEST = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configure Django App for Heroku.
import django_on_heroku
django_on_heroku.settings(locals())

# line 178: uncomment for server use, comment for local use
# del DATABASES['default']['OPTIONS']['sslmode'] 