# Generated by Django 4.1.5 on 2023-01-21 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=5)),
                ('event', models.CharField(max_length=10)),
                ('mark', models.FloatField(default=0.0)),
            ],
        ),
    ]
