# Generated by Django 4.1.5 on 2023-01-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0002_mark_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
            ],
        ),
    ]
