# Generated by Django 4.1.5 on 2023-02-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0006_athlete_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='marks',
        ),
        migrations.AddField(
            model_name='athlete',
            name='eight',
            field=models.TextField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='athlete',
            name='four',
            field=models.TextField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='athlete',
            name='four_h',
            field=models.TextField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='athlete',
            name='four_r',
            field=models.TextField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='athlete',
            name='one',
            field=models.TextField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='athlete',
            name='one_h',
            field=models.TextField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='athlete',
            name='one_r',
            field=models.TextField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='athlete',
            name='sixteen',
            field=models.TextField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='athlete',
            name='thirtytwo',
            field=models.TextField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='athlete',
            name='two',
            field=models.TextField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
