# Generated by Django 4.1.7 on 2023-06-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0009_remove_athlete_eight_remove_athlete_four_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='hj_mark',
            field=models.FloatField(default=0.0, verbose_name='mark'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='hj_points',
            field=models.IntegerField(default=0, verbose_name='points'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='lj_mark',
            field=models.FloatField(default=0.0, verbose_name='mark'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='lj_points',
            field=models.IntegerField(default=0, verbose_name='points'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='pv_mark',
            field=models.FloatField(default=0.0, verbose_name='mark'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='pv_points',
            field=models.IntegerField(default=0, verbose_name='points'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='tj_mark',
            field=models.FloatField(default=0.0, verbose_name='mark'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='tj_points',
            field=models.IntegerField(default=0, verbose_name='points'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='eight_mark',
            field=models.FloatField(default=0.0, verbose_name='mark'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='eight_points',
            field=models.IntegerField(default=0, verbose_name='points'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='four_h_mark',
            field=models.FloatField(default=0.0, verbose_name='mark'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='four_h_points',
            field=models.IntegerField(default=0, verbose_name='points'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='four_mark',
            field=models.FloatField(default=0.0, verbose_name='mark'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='four_points',
            field=models.IntegerField(default=0, verbose_name='points'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='four_r_mark',
            field=models.FloatField(default=0.0, verbose_name='mark'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='four_r_points',
            field=models.IntegerField(default=0, verbose_name='points'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='one_h_mark',
            field=models.FloatField(default=0.0, verbose_name='mark'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='one_h_points',
            field=models.IntegerField(default=0, verbose_name='points'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='one_mark',
            field=models.FloatField(default=0.0, verbose_name='mark'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='one_points',
            field=models.IntegerField(default=0, verbose_name='points'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='one_r_mark',
            field=models.FloatField(default=0.0, verbose_name='mark'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='one_r_points',
            field=models.IntegerField(default=0, verbose_name='points'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='sixteen_mark',
            field=models.FloatField(default=0.0, verbose_name='mark'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='sixteen_points',
            field=models.IntegerField(default=0, verbose_name='points'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='thirtytwo_mark',
            field=models.FloatField(default=0.0, verbose_name='mark'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='thirtytwo_points',
            field=models.IntegerField(default=0, verbose_name='points'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='two_mark',
            field=models.FloatField(default=0.0, verbose_name='mark'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='two_points',
            field=models.IntegerField(default=0, verbose_name='points'),
        ),
    ]
