# Generated by Django 4.1.7 on 2023-06-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0010_athlete_hj_mark_athlete_hj_points_athlete_lj_mark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='dt_mark',
            field=models.FloatField(default=0.0, verbose_name='mark'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='dt_points',
            field=models.IntegerField(default=0, verbose_name='points'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='sp_mark',
            field=models.FloatField(default=0.0, verbose_name='mark'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='sp_points',
            field=models.IntegerField(default=0, verbose_name='points'),
        ),
    ]
