# Generated by Django 4.1.7 on 2023-07-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0011_athlete_dt_mark_athlete_dt_points_athlete_sp_mark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='user',
            field=models.CharField(default='admin', max_length=30),
        ),
        migrations.AddField(
            model_name='mark',
            name='user',
            field=models.CharField(default='admin', max_length=30),
        ),
    ]
