# Generated by Django 4.1.5 on 2023-01-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
