# Generated by Django 4.1.5 on 2023-02-02 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0003_athlete'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='team',
            field=models.CharField(default='Unattached', max_length=50),
            preserve_default=False,
        ),
    ]
