# Generated by Django 4.1.5 on 2023-02-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0004_mark_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='team',
            field=models.CharField(default='Unattached', max_length=50),
            preserve_default=False,
        ),
    ]
