# Generated by Django 4.1.5 on 2023-02-06 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0005_athlete_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='marks',
            field=models.TextField(default='0', max_length=500),
            preserve_default=False,
        ),
    ]
