# Generated by Django 4.1.5 on 2023-02-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0007_remove_athlete_marks_athlete_eight_athlete_four_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='eight',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='four',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='four_h',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='four_r',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='one',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='one_h',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='one_r',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='sixteen',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='thirtytwo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='two',
            field=models.CharField(max_length=20),
        ),
    ]
