# Generated by Django 4.1.7 on 2023-12-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0012_athlete_user_mark_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='grade',
            field=models.IntegerField(default=0, verbose_name='grade'),
        ),
        migrations.AddField(
            model_name='mark',
            name='grade',
            field=models.IntegerField(default=0),
        ),
    ]
